name: pink_ai
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.4
  flutter_markdown: ^0.7.1
  http: ^1.2.1
  flutter:
    sdk: flutter
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
