// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5LV2K_arcsmcFXDwgt4-X45RGdd1BT6s',
    appId: '1:877796491158:web:0f0e97501822c3f078a7b7',
    messagingSenderId: '877796491158',
    projectId: 'pink-ai',
    authDomain: 'pink-ai.firebaseapp.com',
    storageBucket: 'pink-ai.appspot.com',
    measurementId: 'G-DDLJ8VTLMS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHxiTpthsAPOXuymE9WbD3T7BkV8aKlYk',
    appId: '1:877796491158:ios:8481a858db2228eb78a7b7',
    messagingSenderId: '877796491158',
    projectId: 'pink-ai',
    storageBucket: 'pink-ai.appspot.com',
    iosBundleId: 'com.example.pinkAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHxiTpthsAPOXuymE9WbD3T7BkV8aKlYk',
    appId: '1:877796491158:ios:8481a858db2228eb78a7b7',
    messagingSenderId: '877796491158',
    projectId: 'pink-ai',
    storageBucket: 'pink-ai.appspot.com',
    iosBundleId: 'com.example.pinkAi',
  );
}
